site_name: Docs as Craft
repo_url: https://github.com/conceptualshark/portfolio
repo_name: View this repository

# Themes 
theme:
  name: material
  custom_dir: docs/overrides
  icon:
    logo: material/code-braces
  favicon: /assets/images/hero-img.png

  palette: 
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: cyan
      toggle:
        icon: material/brightness-7 
        name: Switch to system preference
        
  features:
    - content.code.copy
    - navigation.top
    - navigation.indexes
    - navigation.expand
    - content.tabs.link
    
plugins:
  - search
  - render_swagger
  - glightbox
  - open-in-new-tab
  
# Extensions 
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.details
  - def_list
  - md_in_html
  - attr_list
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
dev_addr: 0.0.0.0:8080
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/cole-isaac/
    - icon: fontawesome/brands/github
      link: https://github.com/conceptualshark
    - icon: material/email
      link: colegarbo@gmail.com
      name: email
copyright: Copyright &copy; 2025 Cole Isaac Garbo

# CSS and JS overrides 
extra_css:
  - assets/css/overrides.css

# Navigation 
nav:
  - About: about.md
  - Resume: resume.md
  - Portfolio: 
    - portfolio/index.md
    - Guides:
        - Camunda 8 Run: portfolio/guides/c8run.md
        - Git sync for Modeler: portfolio/guides/git-sync.md
        - Remote development (Coder): portfolio/guides/coder.md
        - Fides installation: portfolio/guides/fides-installation-guide.md
        - Fides Privacy Center: portfolio/guides/guide-privacy-center.md
    - Process and planning:
        - Engineering onboarding: portfolio/process/engineering-onboarding.md
        - Enterprise wiki migration: portfolio/process/wiki-migration.md
        - Team foundation: portfolio/process/team-documentation.md
    - Concepts:
        - Privacy regulations: portfolio/concepts/article-privacy-regulations.md
        - Reference architecture: portfolio/concepts/reference-architecture.md
    - References:
        - Privacy requests: portfolio/references/api-privacy-requests.md
        - Referral API: portfolio/references/api-referrals.md




