site_name: Cole Isaac, Technical Writer
repo_url: https://github.com/conceptualshark/portfolio
repo_name: View this repository

# Themes 
theme:
  name: material
  icon:
    logo: simple/readme
  favicon: /assets/images/logo.png

  palette: 
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Light Mode
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: cyan
      toggle:
        icon: material/brightness-7 
        name: Dark Mode
  features:
    - content.code.copy
    - navigation.top
    - navigation.indexes
    
plugins:
  - search
  - render_swagger
  - glightbox
  - open-in-new-tab
  
# Extensions 
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - def_list
  - md_in_html
  - attr_list
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
dev_addr: 0.0.0.0:8080
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/cole-isaac/
    - icon: fontawesome/brands/github
      link: https://github.com/conceptualshark
    - icon: material/email
      link: colegarbo@gmail.com
      name: email
copyright: Copyright &copy; 2023 Cole Isaac Garbo

# CSS and JS overrides 
extra_css:
  - assets/css/overrides.css

# Navigation 
nav:
  - About: index.md
  - Resume: resume.md
  - Portfolio: 
    - portfolio/index.md
    - Guides:
        - Fides installation: portfolio/fides-installation-guide.md
        - Fides Privacy Center: portfolio/guide-privacy-center.md
        - SSL certificates: portfolio/guide-ssl-certificates.md
    - References:
        - Privacy requests: portfolio/api-privacy-requests.md
        - Referrals: portfolio/api-referrals.md
        - Connectors UI: portfolio/guide-connectors.md
    - Concepts:
        - Privacy regulations: portfolio/article-privacy-regulations.md





